#pragma once

#include <string>
#include <unordered_map>

#include "openpilot/cereal/gen/cpp/log.capnp.h"

inline static std::unordered_map<std::string, ParamKeyAttributes> keys = {
    {"AccessToken", {CLEAR_ON_MANAGER_START | DONT_LOG, STRING}},
    {"AdbEnabled", {PERSISTENT, BOOL}},
    {"AlwaysOnDM", {PERSISTENT, BOOL}},
    {"ApiCache_Device", {PERSISTENT, STRING}},
    {"ApiCache_FirehoseStats", {PERSISTENT, JSON}},
    {"AssistNowToken", {PERSISTENT, STRING}},
    {"AthenadPid", {PERSISTENT, INT}},
    {"AthenadUploadQueue", {PERSISTENT, JSON}},
    {"AthenadRecentlyViewedRoutes", {PERSISTENT, STRING}},
    {"BootCount", {PERSISTENT, INT}},
    {"CalibrationParams", {PERSISTENT, BYTES}},
    {"CameraDebugExpGain", {CLEAR_ON_MANAGER_START, STRING}},
    {"CameraDebugExpTime", {CLEAR_ON_MANAGER_START, STRING}},
    {"CarBatteryCapacity", {PERSISTENT, INT}},
    {"CarParams", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BYTES}},
    {"CarParamsCache", {CLEAR_ON_MANAGER_START, BYTES}},
    {"CarParamsPersistent", {PERSISTENT, BYTES}},
    {"CarParamsPrevRoute", {PERSISTENT, BYTES}},
    {"CompletedTrainingVersion", {PERSISTENT, STRING, "0"}},
    {"ControlsReady", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"CurrentBootlog", {PERSISTENT, STRING}},
    {"CurrentRoute", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, STRING}},
    {"DisableLogging", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"DisablePowerDown", {PERSISTENT, BOOL}},
    {"DisableUpdates", {PERSISTENT, BOOL}},
    {"DisengageOnAccelerator", {PERSISTENT, BOOL, "0"}},
    {"DongleId", {PERSISTENT, STRING}},
    {"DoReboot", {CLEAR_ON_MANAGER_START, BOOL}},
    {"DoShutdown", {CLEAR_ON_MANAGER_START, BOOL}},
    {"DoUninstall", {CLEAR_ON_MANAGER_START, BOOL}},
    {"DriverTooDistracted", {CLEAR_ON_MANAGER_START | CLEAR_ON_IGNITION_ON, BOOL}},
    {"DriverLockoutCount", {CLEAR_ON_MANAGER_START | CLEAR_ON_IGNITION_ON, INT, "0"}},
    {"AlphaLongitudinalEnabled", {PERSISTENT | DEVELOPMENT_ONLY, BOOL}},
    {"ExperimentalMode", {PERSISTENT, BOOL}},
    {"ExperimentalModeConfirmed", {PERSISTENT, BOOL}},
    {"FirmwareQueryDone", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"ForcePowerDown", {PERSISTENT, BOOL}},
    {"GitBranch", {PERSISTENT, STRING}},
    {"GitCommit", {PERSISTENT, STRING}},
    {"GitCommitDate", {PERSISTENT, STRING}},
    {"GitDiff", {PERSISTENT, STRING}},
    {"GithubSshKeys", {PERSISTENT, STRING}},
    {"GithubUsername", {PERSISTENT, STRING}},
    {"GitRemote", {PERSISTENT, STRING}},
    {"GsmApn", {PERSISTENT, STRING}},
    {"GsmMetered", {PERSISTENT, BOOL, "1"}},
    {"GsmRoaming", {PERSISTENT, BOOL}},
    {"HardwareSerial", {PERSISTENT, STRING}},
    {"HasAcceptedTerms", {PERSISTENT, STRING, "0"}},
    {"InstallDate", {PERSISTENT, TIME}},
    {"IsDriverViewEnabled", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsEngaged", {PERSISTENT, BOOL}},
    {"IsLdwEnabled", {PERSISTENT, BOOL}},
    {"IsLiveStreaming", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsMetric", {PERSISTENT, BOOL, "1"}},
    {"IsOffroad", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsRhdDetected", {PERSISTENT, BOOL}},
    {"IsReleaseBranch", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsTestedBranch", {CLEAR_ON_MANAGER_START, BOOL}},
    {"JoystickDebugMode", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"LanguageSetting", {PERSISTENT, STRING, "en"}},
    {"LastAthenaPingTime", {CLEAR_ON_MANAGER_START, INT}},
    {"LastGPSPosition", {PERSISTENT, STRING}},
    {"LastManagerExitReason", {CLEAR_ON_MANAGER_START, STRING}},
    {"LastOffroadStatusPacket", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, JSON}},
    {"LastAgnosPowerMonitorShutdown", {CLEAR_ON_MANAGER_START, STRING}},
    {"LastPowerDropDetected", {CLEAR_ON_MANAGER_START, STRING}},
    {"LastUpdateException", {CLEAR_ON_MANAGER_START, STRING}},
    {"LastUpdateRouteCount", {PERSISTENT, INT, "0"}},
    {"LastUpdateTime", {PERSISTENT, TIME}},
    {"LastUpdateUptimeOnroad", {PERSISTENT, FLOAT, "0.0"}},
    {"LiveDelay", {PERSISTENT, BYTES}},
    {"LiveParametersV2", {PERSISTENT, BYTES}},
    {"LivestreamEncoderBitrate", {CLEAR_ON_MANAGER_START | DONT_LOG, INT}},
    {"LivestreamRequestKeyframe", {CLEAR_ON_MANAGER_START | DONT_LOG, BOOL}},
    {"LiveTorqueParameters", {PERSISTENT | DONT_LOG, BYTES}},
    {"LocationFilterInitialState", {PERSISTENT, BYTES}},
    {"LateralManeuverMode", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"LongitudinalManeuverMode", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"LongitudinalPersonality", {PERSISTENT, INT, std::to_string(static_cast<int>(cereal::LongitudinalPersonality::STANDARD))}},
    {"NetworkMetered", {PERSISTENT, BOOL}},
    {"ObdMultiplexingChanged", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"ObdMultiplexingEnabled", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"Offroad_CarUnrecognized", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"Offroad_ConnectivityNeeded", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_ConnectivityNeededPrompt", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_ExcessiveActuation", {PERSISTENT, JSON}},
    {"Offroad_NeosUpdate", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_NoFirmware", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"Offroad_Recalibration", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"Offroad_TemperatureTooHigh", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_UnregisteredHardware", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_UpdateFailed", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_DriverMonitoringUncertain", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"OnroadCycleRequested", {CLEAR_ON_MANAGER_START, BOOL}},
    {"OpenpilotEnabledToggle", {PERSISTENT, BOOL, "1"}},
    {"PandaHeartbeatLost", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"PrimeType", {PERSISTENT, INT}},
    {"RecordAudio", {PERSISTENT, BOOL}},
    {"RecordFront", {PERSISTENT, BOOL}},
    {"RecordFrontLock", {PERSISTENT, BOOL}},  // for the internal fleet
    {"SecOCKey", {PERSISTENT | DONT_LOG, STRING}},
    {"ShowDebugInfo", {PERSISTENT, BOOL}},
    {"RouteCount", {PERSISTENT, INT, "0"}},
    {"SnoozeUpdate", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"SshEnabled", {PERSISTENT, BOOL}},
    {"UbloxAvailable", {PERSISTENT, BOOL}},
    {"UpdateAvailable", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"UpdateFailedCount", {CLEAR_ON_MANAGER_START, INT}},
    {"UpdaterAvailableBranches", {PERSISTENT, STRING}},
    {"UpdaterCurrentDescription", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterCurrentReleaseNotes", {CLEAR_ON_MANAGER_START, BYTES}},
    {"UpdaterFetchAvailable", {CLEAR_ON_MANAGER_START, BOOL}},
    {"UpdaterNewDescription", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterNewReleaseNotes", {CLEAR_ON_MANAGER_START, BYTES}},
    {"UpdaterState", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterTargetBranch", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterLastFetchTime", {PERSISTENT, TIME}},
    {"UptimeOffroad", {PERSISTENT, FLOAT, "0.0"}},
    {"UptimeOnroad", {PERSISTENT, FLOAT, "0.0"}},
    {"UsbGpuActive", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION | CLEAR_ON_IGNITION_ON, BOOL}},
    {"UsbGpuLoading", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION | CLEAR_ON_IGNITION_ON, BOOL}},
    {"Version", {PERSISTENT, STRING}},

    // kisapilot
    {"LongitudinalPersonalityMax", {PERSISTENT, INT, "3"}},
    {"NetworkAddress", {CLEAR_ON_MANAGER_START, STRING}},
    {"ApiCache_NavDestinations", {PERSISTENT, STRING}},
    {"NavDestination", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, STRING}},
    {"NavDestinationWaypoints", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, STRING}},
    {"NavPastDestinations", {PERSISTENT, STRING}},
    {"NavSettingLeftSide", {PERSISTENT, STRING}},
    {"NavSettingTime24h", {PERSISTENT, STRING}},
    {"MapboxStyle", {PERSISTENT, STRING, "0"}},
    {"MapboxPublicKey", {PERSISTENT, STRING}},
    {"MapboxSecretKey", {PERSISTENT, STRING}},
    {"GMapKey", {PERSISTENT, STRING, "0"}},
    {"SearchInput", {PERSISTENT, STRING, "0"}},
    {"SupportedCars", {PERSISTENT, STRING}},
    {"SupportedCars_gm", {PERSISTENT, STRING}},
    {"ShowDebugUI", {PERSISTENT, INT, "0"}},
    {"ShowTpms", {PERSISTENT, INT, "1"}},
    {"ShowDateTime", {PERSISTENT, INT, "1"}},
    {"ShowPathEnd", {PERSISTENT, INT, "1"}},
    {"ShowCustomBrightness", {PERSISTENT, INT, "50"}},
    {"ShowLaneInfo", {PERSISTENT, INT, "2"}},
    {"ShowRadarInfo", {PERSISTENT, INT, "1"}},
    {"ShowDeviceState", {PERSISTENT, INT, "1"}},
    {"ShowRouteInfo", {PERSISTENT, INT, "1"}},
    {"ShowPathMode", {PERSISTENT, INT, "9"}},
    {"ShowPathColor", {PERSISTENT, INT, "13"}},
    {"ShowPathColorCruiseOff", {PERSISTENT, INT, "19"}},
    {"ShowPathModeLane", {PERSISTENT, INT, "14"}},
    {"ShowPathColorLane", {PERSISTENT, INT, "13"}},
    {"ShowPlotMode", {PERSISTENT, INT, "0"}},
    {"RecordRoadCam", {PERSISTENT, INT, "0"}},
    {"HDPuse", {PERSISTENT, INT, "0"}},
    {"AutoCruiseControl", {PERSISTENT, INT, "0"}},
    {"CruiseEcoControl", {PERSISTENT, INT, "0"}},
    {"CarrotCruiseDecel", {PERSISTENT, INT, "-1"}},
    {"CarrotCruiseAtcDecel", {PERSISTENT, INT, "-1"}},
    {"CommaLongAcc", {PERSISTENT, INT, "0"}},
    {"AutoGasTokSpeed", {PERSISTENT, INT, "0"}},
    {"AutoGasSyncSpeed", {PERSISTENT, BOOL, "1"}},
    {"AutoEngage", {PERSISTENT, INT, "0"}},
    {"DisableMinSteerSpeed", {PERSISTENT, INT, "0"}},
    {"SoftHoldMode", {PERSISTENT, INT, "0"}},
    {"AutoSpeedUptoRoadSpeedLimit", {PERSISTENT, INT, "10"}},
    {"AutoRoadSpeedAdjust", {PERSISTENT, INT, "-1"}},
    {"AutoCurveSpeedLowerLimit", {PERSISTENT, INT, "40"}},
    {"AutoCurveSpeedFactor", {PERSISTENT, INT, "80"}},
    {"AutoTurnControl", {PERSISTENT, INT, "0"}},
    {"AutoTurnControlSpeedTurn", {PERSISTENT, INT, "20"}},
    {"AutoTurnControlTurnEnd", {PERSISTENT, INT, "6"}},
    {"AutoTurnMapChange", {PERSISTENT, INT, "0"}},
    {"AutoNaviSpeedCtrlEnd", {PERSISTENT, INT, "8"}},
    {"AutoNaviSpeedCtrlMode", {PERSISTENT, INT, "2"}},
    {"AutoRoadSpeedLimitOffset", {PERSISTENT, INT, "10"}},
    {"AutoNaviSpeedBumpTime", {PERSISTENT, INT, "2"}},
    {"AutoNaviSpeedBumpSpeed", {PERSISTENT, INT, "30"}},
    {"AutoNaviSpeedDecelRate", {PERSISTENT, FLOAT, "1.2"}},
    {"AutoNaviSpeedSafetyFactor", {PERSISTENT, INT, "102"}},
    {"AutoNaviCountDownMode", {PERSISTENT, INT, "0"}},
    {"TurnSpeedControlMode", {PERSISTENT, INT, "1"}},
    {"MapTurnSpeedFactor", {PERSISTENT, INT, "90"}},
    {"ModelTurnSpeedFactor", {PERSISTENT, FLOAT, "0.0"}},
    {"StoppingAccel", {PERSISTENT, FLOAT, "0.0"}},
    {"StopDistanceCarrot", {PERSISTENT, FLOAT, "3.3"}},
    {"JLeadFactor3", {PERSISTENT, FLOAT, "0.65"}},
    {"CruiseButtonMode", {PERSISTENT, INT, "0"}},
    {"CancelButtonMode", {PERSISTENT, INT, "0"}},
    {"LfaButtonMode", {PERSISTENT, INT, "0"}},
    {"CruiseButtonTest1", {PERSISTENT, INT, "8"}},
    {"CruiseButtonTest2", {PERSISTENT, INT, "30"}},
    {"CruiseButtonTest3", {PERSISTENT, INT, "1"}},
    {"CruiseSpeedUnit", {PERSISTENT, INT, "10"}},
    {"CruiseSpeedUnitBasic", {PERSISTENT, INT, "10"}},
    {"CruiseSpeed1", {PERSISTENT, INT, "0"}},
    {"CruiseSpeed2", {PERSISTENT, INT, "50"}},
    {"CruiseSpeed3", {PERSISTENT, INT, "80"}},
    {"CruiseSpeed4", {PERSISTENT, INT, "110"}},
    {"CruiseSpeed5", {PERSISTENT, INT, "130"}},
    {"PaddleMode", {PERSISTENT, INT, "2"}},
    {"MyDrivingMode", {PERSISTENT, INT, "3"}},
    {"MyDrivingModeAuto", {PERSISTENT, INT, "0"}},
    {"TrafficLightDetectMode", {PERSISTENT, INT, "2"}},
    {"CruiseMaxVals0", {PERSISTENT, FLOAT, "1.65"}},
    {"CruiseMaxVals1", {PERSISTENT, FLOAT, "1.55"}},
    {"CruiseMaxVals2", {PERSISTENT, FLOAT, "0.8"}},
    {"CruiseMaxVals3", {PERSISTENT, FLOAT, "0.6"}},
    {"CruiseMaxVals4", {PERSISTENT, FLOAT, "0.4"}},
    {"CruiseMaxVals5", {PERSISTENT, FLOAT, "0.3"}},
    {"CruiseMaxVals6", {PERSISTENT, FLOAT, "0.2"}},
    {"LongTuningKpV", {PERSISTENT, FLOAT, "0.5"}},
    {"LongTuningKiV", {PERSISTENT, FLOAT, "0.1"}},
    {"LongActuatorDelay", {PERSISTENT, FLOAT, "0.2"}},
    {"VEgoStopping", {PERSISTENT, FLOAT, "0.05"}},
    {"RadarReactionFactor", {PERSISTENT, FLOAT, "1.1"}},
    {"EnableRadarTracks", {PERSISTENT, INT, "3"}},
    {"RadarLatFactor", {PERSISTENT, FLOAT, "2.0"}},
    {"EnableCornerRadar", {PERSISTENT, INT, "1"}},
    {"HyundaiCameraSCC", {PERSISTENT, INT, "1"}},
    {"FingerPrints", {PERSISTENT | CLEAR_ON_MANAGER_START, STRING}},
    {"IsLdwsCar", {PERSISTENT, INT, "0"}},
    {"CanfdHDA2", {PERSISTENT, INT, "2"}},
    {"CanfdDebug", {PERSISTENT, INT, "0"}},
    {"SoundVolumeAdjust", {PERSISTENT, INT, "100"}},
    {"SoundVolumeAdjustEngage", {PERSISTENT, INT, "50"}},
    {"TFollowGap1", {PERSISTENT, FLOAT, "0.9"}},
    {"TFollowGap2", {PERSISTENT, FLOAT, "1.1"}},
    {"TFollowGap3", {PERSISTENT, FLOAT, "1.3"}},
    {"TFollowGap4", {PERSISTENT, FLOAT, "1.6"}},
    {"DynamicTFollow", {PERSISTENT, FLOAT, "0.0"}},
    {"TrafficStopDistanceAdjust", {PERSISTENT, FLOAT, "0.0"}},
    {"DynamicTFollowLC", {PERSISTENT, FLOAT, "1.0"}},
    {"AChangeCostStarting", {PERSISTENT, FLOAT, "10.0"}},
    {"HapticFeedbackWhenSpeedCamera", {PERSISTENT, INT, "3"}},
    {"UseLaneLineSpeed", {PERSISTENT, INT, "20"}},
    {"PathOffset", {PERSISTENT, FLOAT, "0.0"}},
    {"UseLaneLineCurveSpeed", {PERSISTENT, INT, "60"}},
    {"CameraOffsetAdj", {PERSISTENT, FLOAT, "0.0"}},
    {"AdjustLaneOffset", {PERSISTENT, FLOAT, "0.0"}},
    {"LaneChangeNeedTorque", {PERSISTENT, INT, "0"}},
    {"LaneChangeDelay", {PERSISTENT, FLOAT, "0.5"}},
    {"LaneChangeBsd", {PERSISTENT, INT, "0"}},
    {"MaxAngleFrames", {PERSISTENT, INT, "89"}},
    {"LateralTorqueCustom", {PERSISTENT, INT, "0"}},
    {"LateralTorqueAccelFactor", {PERSISTENT, FLOAT, "2.5"}},
    {"LateralTorqueFriction", {PERSISTENT, FLOAT, "0.1"}},
    {"LateralTorqueKpV", {PERSISTENT, INT, "100"}},
    {"LateralTorqueKiV", {PERSISTENT, INT, "10"}},
    {"LateralTorqueKf", {PERSISTENT, INT, "100"}},
    {"LateralTorqueKd", {PERSISTENT, INT, "0"}},
    {"LatMpcPathCost", {PERSISTENT, INT, "200"}},
    {"LatMpcMotionCost", {PERSISTENT, INT, "7"}},
    {"LatMpcAccelCost", {PERSISTENT, INT, "120"}},
    {"LatMpcJerkCost", {PERSISTENT, INT, "4"}},
    {"LatMpcSteeringRateCost", {PERSISTENT, INT, "7"}},
    {"LatMpcInputOffset", {PERSISTENT, INT, "4"}},
    {"CustomSteerMax", {PERSISTENT, INT, "0"}},
    {"CustomSteerDeltaUp", {PERSISTENT, INT, "0"}},
    {"CustomSteerDeltaDown", {PERSISTENT, INT, "0"}},
    {"CustomSteerDeltaUpLC", {PERSISTENT, INT, "0"}},
    {"CustomSteerDeltaDownLC", {PERSISTENT, INT, "0"}},
    {"SteerActuatorDelay", {PERSISTENT, FLOAT, "0.0"}},
    {"LatSmoothSec", {PERSISTENT, FLOAT, "0.13"}},
    {"MaxTimeOffroadMin", {PERSISTENT, INT, "60"}},
    {"EnableConnect", {PERSISTENT, INT, "0"}},
    {"MuteDoor", {PERSISTENT, BOOL, "0"}},
    {"MuteSeatbelt", {PERSISTENT, BOOL, "0"}},
    {"CarrotException", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    {"CarrotSpeed", {PERSISTENT, INT, "0"}},
    {"CarrotSpeedTable", {PERSISTENT, BYTES}},
    {"CarName", {PERSISTENT, STRING, ""}},
    {"EVTable", {PERSISTENT, BOOL, "1"}},
    {"LongPitch", {PERSISTENT, BOOL, "1"}},
    {"ActivateCruiseAfterBrake", {CLEAR_ON_MANAGER_START, BOOL}},
    {"CustomSR", {PERSISTENT, FLOAT, "0.0"}},
    {"CarrotSpeedViz", {PERSISTENT, STRING}},
    {"SteerRatioRate", {PERSISTENT, INT, "100"}},
    {"SoftRestartTriggered", {CLEAR_ON_MANAGER_START, INT}},
    {"DevicePosition", {CLEAR_ON_MANAGER_START, STRING}},
    {"NNFF", {PERSISTENT, BOOL, "0"}},
    {"NNFFLite", {PERSISTENT, BOOL, "0"}},
    {"NNFFModelName", {CLEAR_ON_OFFROAD_TRANSITION, STRING}},
    {"HardwareC3xLite", {PERSISTENT, BOOL}},
    {"CarrotSmartSpeedControl", {PERSISTENT, INT, "0"}},
    {"CruiseOnDist", {PERSISTENT, FLOAT, "4.0"}},
    {"EyeThreshold", {PERSISTENT, INT, "35"}},
    {"BlinkThreshold", {PERSISTENT, INT, "65"}},
    {"KisaEnableLogger", {PERSISTENT, BOOL, "0"}},
    {"KisaCANType", {PERSISTENT, STRING, "-"}},
    {"KisaSCCType", {PERSISTENT, STRING, "-"}},
    {"PutPrebuiltOn", {PERSISTENT, BOOL, "0"}},
    {"IsOpenpilotViewEnabled", {CLEAR_ON_MANAGER_START, BOOL}},
    {"KisaBlindSpotDetect", {PERSISTENT, BOOL, "1"}},
    {"KisaSSHLegacy", {PERSISTENT, BOOL, "1"}},
    {"RecordingRunning", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL, "0"}},
    {"RecordingTimePerVideo", {PERSISTENT, INT, "5"}},
    {"RecordingMaxFiles", {PERSISTENT, INT, "200"}},
    {"OnRoadRefresh", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    {"CanParserResult", {PERSISTENT, STRING}},
    {"AChangeCost2", {PERSISTENT, INT, "125"}},
    {"CameraOffsetAdj", {PERSISTENT, FLOAT, "0.04"}},
    {"CarList", {PERSISTENT, STRING, "Select Your Car"}},
    {"GitCommits", {CLEAR_ON_MANAGER_START, STRING}},
    {"EnableSpeedTF", {PERSISTENT, INT, "0"}},
    {"LeftEdgeOffset", {PERSISTENT, FLOAT, "-0.05"}},
    {"RightEdgeOffset", {PERSISTENT, FLOAT, "0.05"}},
    {"CameraYawTrimDeg", {PERSISTENT, FLOAT, "0.0"}},
    {"CarrotNaviDebug", {CLEAR_ON_MANAGER_START, STRING} },
    {"CarrotNaviImage", {CLEAR_ON_MANAGER_START, STRING} },
    {"TrafficLight", {CLEAR_ON_MANAGER_START, STRING} },
};
